[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "SotoEstevez", email = "ricardo@sotoestevez.dev" }
]
requires-python = ">=3.13"
dependencies = [
    "datasets>=5.0.1",
    "pyvespa>=1.2.4",
]

[project.scripts]
query = "scripts.query:query"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
