# Runs all the integration tests (they require the Docker to be running locally)
[group("test")]
@integration:
  cd ./client && cargo test -- --ignored

# Executes all the examples to validate they still work
[group("test")]
@examples:
  cd ./client && cargo run --example search
